#!/usr/bin/ruby

test_names = Dir['examples/*.sim'].map { |s| s.match(/\/([A-Za-z0-9_]*)/)[1] }

succesful_tests = 0
failed_tests = 0

test_names.each do |name|
  error = `./sc #{ARGV[0]} examples/#{name}.sim #{ARGV[1]} 2>&1`
  status = $?.exitstatus
  if status == 0
    puts "\e[32m$$  Test '#{name}' was successful.\e[0m"
    succesful_tests += 1
  else
    puts "\e[31m!!  Test '#{name}' failed with output:\e[0m"
    puts "^^  #{error.chomp.gsub /\n/, "\n^^  "}"
    failed_tests += 1
  end
end

total_tests = succesful_tests + failed_tests

puts '+++++++++++++++++++++++++++++++++++++++++++'
print "#{total_tests} tests #{(total_tests > 1) ? 'were' : 'was'}"
puts " run with #{succesful_tests} succesful, #{failed_tests} failed."

