#!/bin/bash

if [ ! $1 ]; then
  echo error: usage: ./test file_prefix
elif [ ! -e $1.sim ]; then
  echo error: $1.sim does not exist
else
  echo ":::::::::::::::::"
  echo "   interpreter   "
  echo ":::::::::::::::::"
  ./sc -i $1.sim
  echo ":::::::::::::::::"
  echo "      lazy       "
  echo ":::::::::::::::::"
  ./sc $1.sim
  gcc $1.s
  ./a.out
  echo ":::::::::::::::::"
  echo "    improved     "
  echo ":::::::::::::::::"
  ./sc -x $1.sim
  gcc $1.s
  ./a.out
fi

